{% set name = "cfitsio" %}
{% set version = "4.4.0" %}
# This is the SHA256 hash of the ungzipped tar file. See https://github.com/conda/conda/issues/3798.
{% set sha256 = "c42bd609151c0b0d7c4f3578d425ae7aaa9afa4828cab35c0accea588e290c29" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ldflags.patch
    - unvendor_zlib.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('cfitsio', max_pin='x.x.x') }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [not win]
  host:
    - libcurl
    - bzip2  # [not win]
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libcfitsio{{ SHLIB_EXT }}  # [not win]
    - if not exist %LIBRARY_LIB%\cfitsio.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\cfitsio.dll exit 1  # [win]
  # Downstream tests are not possible due to cfitsio being pinned to a specific
  # major.minor.patch version in conda-forge-pinning. E.g. gdal is currently
  # build pinned against cfitsio 4.0.0, which means we cannot test a new version
  # of cfitsio (4.1.0 say) in a downstream test of gdal.
  # Downstream tests could be enabled again if there are no foreseeable new versions
  # cfitsio.
#  downstreams:
#    - gdal  # [x86_64]

about:
  home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  license: NASA-1.3
  license_file: licenses/NASA_Open_Source_Agreement_1.3.txt
  summary: A library for reading and writing FITS files

  description: |
    CFITSIO is a library of C and Fortran subroutines for reading and writing
    data files in FITS (Flexible Image Transport System) data format. CFITSIO
    provides simple high-level routines for reading and writing FITS files that
    insulate the programmer from the internal complexities of the FITS format.
    CFITSIO also provides many advanced features for manipulating and filtering
    the information in FITS files.
  doc_url: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/quick.html

extra:
  recipe-maintainers:
    - pkgw
    - teake
